version: '3.8'

services:
  test_report_app:
    build: 
      context: ./
      dockerfile: Dockerfile
    volumes:
      - static_volume:/opt/app/test_report_app/static  # <-- bind the static volume
      - media_volume:/opt/app/test_report_app/media  # <-- bind the media volume
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    ports:
      - 8181:8181
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/app/test_report_app/static  # <-- bind the static volume
      - media_volume:/opt/app/test_report_app/media  # <-- bind the media volume
    depends_on:
      - test_report_app
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume