# Generated by Django 5.0 on 2023-12-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=40)),
                ("firmware_version", models.CharField(max_length=15)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("short_circuit", models.BooleanField(default=False)),
                ("usb_connection", models.BooleanField(default=False)),
                ("modbus_connection", models.BooleanField(default=False)),
                ("optical_sensor", models.BooleanField(default=False)),
                ("encoder", models.BooleanField(default=False)),
                ("optical_learning", models.BooleanField(default=False)),
                ("channels", models.BooleanField(default=False)),
                ("tester", models.CharField(max_length=50)),
            ],
        ),
    ]
