# Generated by Django 5.0 on 2023-12-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_tested", "Не проверена"),
                    ("tested", "Проверена"),
                    ("need_repair", "В ремонте"),
                ],
                default="not_tested",
                max_length=40,
            ),
        ),
    ]
