# Generated by Django 5.0 on 2023-12-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_report_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="comment",
            field=models.TextField(
                default=models.CharField(
                    choices=[
                        ("not_tested", "Не проверена"),
                        ("tested", "Проверена"),
                        ("need_repair", "В ремонте"),
                    ],
                    default="not_tested",
                    max_length=40,
                ),
                max_length=140,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="channels",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="encoder",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="modbus_connection",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="optical_learning",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="optical_sensor",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="short_circuit",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="usb_connection",
            field=models.BooleanField(default=True),
        ),
    ]
