# Generated by Django 5.0 on 2023-12-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_report_comment_alter_report_channels_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="comment",
            field=models.TextField(max_length=140),
        ),
    ]
