# Generated by Django 5.0 on 2023-12-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_alter_report_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="channels",
            field=models.BooleanField(default=True, verbose_name="Каналы"),
        ),
        migrations.AlterField(
            model_name="report",
            name="comment",
            field=models.TextField(
                blank=True, max_length=140, verbose_name="Комментарии"
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateField(auto_now_add=True, verbose_name="Дата"),
        ),
        migrations.AlterField(
            model_name="report",
            name="encoder",
            field=models.BooleanField(default=True, verbose_name="Энкодер"),
        ),
        migrations.AlterField(
            model_name="report",
            name="firmware_version",
            field=models.CharField(max_length=15, verbose_name="Прошивка"),
        ),
        migrations.AlterField(
            model_name="report",
            name="modbus_connection",
            field=models.BooleanField(default=True, verbose_name="MODBUS соединение"),
        ),
        migrations.AlterField(
            model_name="report",
            name="optical_learning",
            field=models.BooleanField(default=True, verbose_name="Обучение"),
        ),
        migrations.AlterField(
            model_name="report",
            name="optical_sensor",
            field=models.BooleanField(default=True, verbose_name="Отметчик"),
        ),
        migrations.AlterField(
            model_name="report",
            name="serial_number",
            field=models.CharField(max_length=40, verbose_name="Серийный номер"),
        ),
        migrations.AlterField(
            model_name="report",
            name="short_circuit",
            field=models.BooleanField(default=True, verbose_name="Короткое замыкание"),
        ),
        migrations.AlterField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_tested", "Не проверена"),
                    ("tested", "Проверена"),
                    ("need_repair", "В ремонте"),
                ],
                default="not_tested",
                max_length=40,
                verbose_name="Состояние",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="tester",
            field=models.CharField(max_length=50, verbose_name="Тестировал"),
        ),
        migrations.AlterField(
            model_name="report",
            name="usb_connection",
            field=models.BooleanField(default=True, verbose_name="USB соединение"),
        ),
    ]
